web-master/web-backend/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
        # 홈 화면
        path('', views.HomeView.as_view(), name='home'),

        # 과목 메인 화면
        path('<title>/', views.SubjectView.as_view(), name='subject'),

        # 과목 상세 화면(과제 목록 확인, 과제 출제)
        path('<title>/<int:year>/<class_no>', views.SubjectDetailView.as_view(), name='subject_detail'),

        # 과제 등록 화면
        path('<title>/<int:year>/<class_no>/assignment/new/', views.AssignmentEditView.as_view(), name='assignment_new'),
        path('<title>/<int:year>/<class_no>/assignment/new/compile', views.compile, name='compile'),
        
        # 과제 상세 화면(과제 상세 확인, 과제 제출, 과제 수정)
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/', views.AssignmentView.as_view(), name='assignment_detail'),
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/input', views.assignment_input, name='assignment_input'),
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/assignment_input_output_setting', views.assignment_input_output_setting, name='assignment_input_output_setting'),
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/compile', views.assignment_compile, name='assignment_compile'),

        # 과제 점수 등록
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/jumsu/', views.AssignmentView.as_view(), name='jumsu'),

        # 제출된 과제 일괄 다운로드
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/download/', views.download_submitted_assignment_files, name='download'),

        # 게시글 상세 화면, 댓글 등록 화면
        path('<title>/boards/<int:pk>/', views.PostView.as_view(), name='post_detail'),
        
        # 게시글 등록 화면
        path('<title>/boards/new/', views.NewPostView.as_view(), name='post_new'),

        # 게시글 수정
        path('<title>/boards/<int:pk>/edit', views.PostEditView.as_view(), name='post_edit'),

        # 게시글 수정 화면에서 코드 리턴해주기
        path('<title>/boards/<int:pk>/edit/<filename>', views.PostEditView.as_view(), name='post_edit'),

        # 게시글 삭제
        path('<title>/boards/<int:pk>/delete', views.post_delete, name='post_delete'),

        # 게시글에서 코드 리턴해주기
        path('<title>/boards/<int:pk>/<filename>', views.get_source_code, name='get_source_code'),
        
        # 댓글 수정
        path('<title>/boards/<int:p_pk>/comment_edit/<int:c_pk>/', views.CommentEditView.as_view(), name='comment_edit'),

        # 댓글 삭제
        path('<title>/boards/<int:p_pk>/comment_delete/<int:c_pk>/', views.comment_delete, name='comment_delete'),
]

web-master/web-backend/shell/models.py
from django.db import models
from accounts.models import User
from django.conf import settings  
# Create your models here.

class Container(models.Model):
    
    user = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=False, 
        primary_key=True,
    )

    username = models.CharField(
        null= True,
        max_length=30,
    )

    osname = models.CharField(
        null= True,
        max_length=30,
    )

    flag = models.BooleanField(
        'flag',
        default=False,
    )

    ipaddr = models.CharField(
        'container ip address',
        max_length=30,
        blank=True,
        default=None,
        null=True,
    )
    def __str__(self):
        return self.user.uos_id

web-master/web-backend/shell/views.py
from django.shortcuts import render, redirect
from .models import Container
from django.urls import reverse_lazy
from project import views as project_views
from subprocess import Popen
import os

def shell_view(request):
    containers = Container.objects.get(user=request.user)
    

    if containers.ipaddr != "":
        split_ipaddress = containers.ipaddr.split('.')

        context = {
            'is_created': containers.flag,
            'container_ip': containers.ipaddr,
            'container_port': int(split_ipaddress[3])+20000,
        }

    else:
         context = {
            'is_created': containers.flag,
            'container_ip': containers.ipaddr,
            'container_port': '',
        }
        
    return render(request, 'shell.html', context)
    
def create_container(request):
    
    containers = Container.objects.get(user=request.user)

    containers.flag = True
    os_name = request.POST.get('os')
    containers.osname = os_name

    containers.save()

    username = request.user.uos_id
    
    print(os_name)
    print(username)

    Popen(["/root/openstack/scripts/make_instance.sh" , username ,os_name ])
 #   os.system("/root/openstack/scripts/make_instance.sh" + " " + username + " " + os_name)

    return redirect('home') 

def delete_container(request):

    containers = Container.objects.get(user=request.user)

    if containers.flag == True:
        containers.flag = False
        containers.ipaddr = ""

        os_name = containers.osname
        username = request.user.uos_id

        containers.osname =""

        print(os_name)
        print(username)

        containers.save()
#       Popen(["/root/openstack/scripts/delete_container_with_user_id_and_user_os.sh" , username ,os_name ])
        os.system("/root/openstack/scripts/delete_container_with_user_id_and_user_os.sh" + " " + username + " " + os_name)

        return redirect('/shell')

    else:
        return redirect('/shell')

web-master/web-backend/templates/activation_email.html
<html>
    <body>
        {{ user }}님, 아래 링크를 클릭하여 계정을 활성화하세요.<br>
        <a href="http://{{ domain }}{% url 'activate' uid token %}">http://{{ domain }}{% url 'activate' uid token %}</a>
    </body>
</html>

web-master/web-backend/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <title>{% block title %}BASE TEMPLATE{% endblock title %}</title>

        <link rel="shortcut icon" href="{% static 'base/img/favicon.ico' %}">
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'base/css/custom-bs.css' %}">
        <link rel="stylesheet" href="{% static 'base/css/jquery.fancybox.min.css' %}">
        <link rel="stylesheet" href="{% static 'base/fonts/icomoon/style.css' %}">
        <link rel="stylesheet" href="{% static 'base/fonts/line-icons/style.css' %}">

        <!-- MAIN CSS -->
        <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
        {% block style %}
        {% endblock style %}
    </head>


    <body>

        <div id="overlayer"></div>
        
        <div class="loader">
            <div class="spinner-border text-primary" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>


        <div class="site-wrap">

            <div class="site-mobile-menu site-navbar-target">
                <div class="site-mobile-menu-header">
                    <div class="site-mobile-menu-close mt-3">
                        <span class="icon-close2 js-menu-toggle"></span>
                    </div>
                </div>
                <div class="site-mobile-menu-body"></div>
            </div> <!-- .site-mobile-menu -->


            <!-- NAVBAR -->
            <header class="site-navbar mt-3" id="top">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="site-logo col-6">
                            <a href="{% url 'home' %}"><img src="{% static 'base/img/server_b_logo_white.png' %}" width="150" height="50" alt=""></a>
                        </div>

                        <nav class="mx-auto site-navigation">
                            <ul class="site-menu js-clone-nav d-none d-lg-block">

                            {% if user.is_active %}
                                <li><a href="{% url 'home' %}" class="nav-link active">Home</a></li>
                                <li><a href="{% url 'shell' %}">Shell</a></li>
                                <li><a href="{% url 'upload_file' %}">Web Hosting</a></li>
                                
                                <li class="has-children">
                                    <a href="{% url 'boards:home' %}">Boards</a>
                                    <ul class="dropdown">

                                        <li class="has-children">
                                            <a href="{% url 'boards:home' %}">1학년</a>
                                            <ul class="dropdown">
                                                <li><a href="{% url 'boards:subject' title='컴퓨터개론' %}">컴퓨터개론</a></li>
                                                <li><a href="{% url 'boards:subject' title='프로그래밍입문' %}">프로그래밍입문</a></li>
                                                <li><a href="{% url 'boards:subject' title='C언어및실습' %}">C언어및실습</a></li>
                                                <li><a href="{% url 'boards:subject' title='창의공학기초설계' %}">창의공학기초설계</a></li>
                                            </ul>
                                        </li>

                                        <li class="has-children">
                                            <a href="{% url 'boards:home' %}">2학년 1학기</a>
                                            <ul class="dropdown">
                                                <li><a href="{% url 'boards:subject' title='논리회로및실습' %}">논리회로및실습</a></li>
                                                <li><a href="{% url 'boards:subject' title='이산수학' %}">이산수학</a></li>
                                                <li><a href="{% url 'boards:subject' title='객체지향프로그래밍및실습' %}">객체지향프로그래밍및실습</a></li>
                                                <li><a href="{% url 'boards:subject' title='멀티미디어응용' %}">멀티미디어응용</a></li>
                                                <li><a href="{% url 'boards:subject' title='선형대수' %}">선형대수</a></li>
                                                <li><a href="{% url 'boards:subject' title='확률과통계' %}">확률과통계</a></li>	
                                            </ul>
                                        </li>

                                        <li class="has-children">
                                            <a href="{% url 'boards:home' %}">2학년 2학기</a>
                                            <ul class="dropdown">
                                                <li><a href="{% url 'boards:subject' title='자료구조' %}">자료구조</a></li>
                                                <li><a href="{% url 'boards:subject' title='데이터통신' %}">데이터통신</a></li>
                                                <li><a href="{% url 'boards:subject' title='수리모형과미분방정식' %}">수리모형과미분방정식</a></li>
                                                <li><a href="{% url 'boards:subject' title='유닉스프로그래밍' %}">유닉스프로그래밍</a></li>
                                                <li><a href="{% url 'boards:subject' title='인터넷프로그래밍및실습' %}">인터넷프로그래밍및실습</a></li>
                                                <li><a href="{% url 'boards:subject' title='프로그래밍언어론' %}">프로그래밍언어론</a></li>	
                                            </ul>
                                        </li>

                                        <li class="has-children">
                                            <a href="{% url 'boards:home' %}">3학년 1학기</a>
                                            <ul class="dropdown">
                                                <li><a href="{% url 'boards:subject' title='운영체제' %}">운영체제</a></li>
                                                <li><a href="{% url 'boards:subject' title='윈도우즈프로그래밍' %}">윈도우즈프로그래밍</a></li>
                                                <li><a href="{% url 'boards:subject' title='컴퓨터구조론' %}">컴퓨터구조론</a></li>
                                                <li><a href="{% url 'boards:subject' title='컴퓨터보안' %}">컴퓨터보안</a></li>
                                                <li><a href="{% url 'boards:subject' title='윈도우즈프로그래밍' %}">컴퓨터알고리즘</a></li>
                                                <li><a href="{% url 'boards:subject' title='컴퓨터통신' %}">컴퓨터통신</a></li> 
                                                <li><a href="{% url 'boards:subject' title='화일처리론' %}">화일처리론</a></li> 
                                            </ul>
                                        </li>

                                        <li class="has-children">
                                            <a href="{% url 'boards:home' %}">3학년 2학기</a>
                                            <ul class="dropdown">
                                                <li><a href="{% url 'boards:subject' title='소프트웨어공학' %}">소프트웨어공학</a></li>
                                                <li><a href="{% url 'boards:subject' title='윈도우즈프로그래밍' %}">데이터베이스</a></li>
                                                <li><a href="{% url 'boards:subject' title='마이크로프로세서설계및실습' %}">마이크로프로세서설계및실습</a></li>
                                                <li><a href="{% url 'boards:subject' title='소프트웨어응용' %}">소프트웨어응용</a></li>
                                                <li><a href="{% url 'boards:subject' title='윈도우즈프로그래밍' %}">인공지능</a></li>
                                                <li><a href="{% url 'boards:subject' title='임베디드시스템설계' %}">임베디드시스템설계</a></li>
                                            </ul>
                                        </li>

                                        <li class="has-children">
                                            <a href="{% url 'boards:home' %}">4학년 1학기</a>
                                            <ul class="dropdown">
                                                <li><a href="{% url 'boards:subject' title='컴퓨터과학종합설계' %}">컴퓨터과학종합설계</a></li>
                                                <li><a href="{% url 'boards:subject' title='윈도우즈프로그래밍' %}">데이터베이스설계</a></li>
                                                <li><a href="{% url 'boards:subject' title='멀티미디어개론' %}">멀티미디어개론</a></li>
                                                <li><a href="{% url 'boards:subject' title='모바일소프트웨어설계' %}">모바일소프트웨어설계</a></li>
                                                <li><a href="{% url 'boards:subject' title='윈도우즈프로그래밍' %}">웹정보시스템</a></li>
                                                <li><a href="{% url 'boards:subject' title='컴파일러구성' %}">컴파일러구성</a></li> 
                                                <li><a href="{% url 'boards:subject' title='클라우드컴퓨팅' %}">클라우드컴퓨팅</a></li> 
                                            </ul>
                                        </li>

                                        <li class="has-children">
                                            <a href="{% url 'boards:home' %}">4학년 2학기</a>
                                            <ul class="dropdown">
                                                <li><a href="{% url 'boards:subject' title='컴퓨터과학종합설계' %}">컴퓨터과학종합설계</a></li>
                                                <li><a href="{% url 'boards:subject' title='IT벤쳐창업실무(융.복합)' %}">IT벤쳐창업실무(융.복합)</a></li>
                                                <li><a href="{% url 'boards:subject' title='네트워크보안' %}">네트워크보안</a></li>
                                                <li><a href="{% url 'boards:subject' title='윈도우즈프로그래밍' %}">컴퓨터그래픽스</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                
                                <li class="has-children">
                                    <a href="{% url 'mypage' %}">{{ user.name }}</a>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'logout' %}">Logout</a></li>
                                    </ul>
                                </li>
                            {% endif %}

                            </ul>
                        </nav>

                        <div class="col-6 site-burger-menu d-block d-lg-none text-right">
                            <a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu h3"></span></a>
                        </div>

                    </div>
                </div>
            </header>


            <!-- HOME -->
            
        {% block only-for-home %}
            <section class="home-section home-section-hero overlay" id="home-section">
                <div class="container">	
                </div>		
            </section>

            <section class="content" id="content">
                <div class="container">	
                {% block content %}
                {% endblock content %}        
                </div>
            </section>
        {% endblock only-for-home %}

        {% block home-content %}
        {% endblock home-content %}
        
            <!-- FOOTER -->
            <footer class="site-footer {% block footer-class %}site-footer-base{% endblock footer-class %}">

                {% block footer-button %}
                {% endblock footer-button %}

                <div class="container">
                    <div class="row mb-5"></div>

                    <div class="row text-center">
                        <div class="col-12">
                            <p class="copyright"><small class="block">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved by Server-B | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </small></p>
                        </div>
                    </div>
                </div>
            </footer>

        </div>


        <!-- SCRIPTS -->
        <script src="{% static 'base/js/jquery.min.js' %}"></script>
        <script src="{% static 'base/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'base/js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'base/js/stickyfill.min.js' %}"></script>
        <script src="{% static 'base/js/jquery.fancybox.min.js' %}"></script>
        <script src="{% static 'base/js/jquery.easing.1.3.js' %}"></script>

        <script src="{% static 'base/js/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'base/js/jquery.animateNumber.min.js' %}"></script>

        <script src="{% static 'base/js/custom.js' %}"></script>
    </body>
</html>

web-master/web-backend/templates/shell.html
{% extends "base.html" %}
{% load static %}

{% block title %}SHELL{% endblock title %}

{% block content %}
{% if is_created == True %} <!-- 생성 시도가 이루어졌을 때 --->
    {% if container_ip != "" %} <!-- IP가 배정되었다면 --->
    <h4>Initial ID : {{ user.get_username }} / Initial PW : password</h4>
    <iframe src="http://172.16.163.38:{{ container_port }}" width="100%" height="1000" frameBorder="0" scrolling="no"> Shellinabox </iframe>

    {% else %} <!-- IP가 배정되지 않았다면 --->
    <h2 class="creating_container">We are creating Container now.<br>Please try again.<br>It will take about 2 minutes.</h2>
    {% endif %}

    {% else %} <!-- 생성 시도가 없었다면 --->
    {% if container_ip != "" %}

<h2 class="problem_container"> Problem Occured!<br>Please delete your container in Mypage. </h2>
    {% else %}

<h2 class="check_container">CREATE CONTAINER NOW. CHECK PLEASE.</h2>

<div class="wrapper_os">
    <div class="logo_os">
        <img src="{% static 'base/img/centos.png' %}" width="80px" height="80px">
    </div>
    <div class="explain_os">
        <p>CentOS7 1907</p>
    </div>   
    <form method= "POST" action="{% url 'create_container' %}">
        {% csrf_token %}
        <button name="os" value="centos7" class="submit_container">Build</button>
    </form>
</div>

<div class="wrapper_os">
    <div class="logo_os">
        <img src="{% static 'base/img/ubuntu.png' %}" width="80px" height="80px">
    </div>
    <div class="explain_os">
        <p>Ubuntu 16.04 LTS</p>
    </div>   
    <form method= "POST" action="{% url 'create_container' %}">
        {% csrf_token %}
        <button name="os" value="ubuntu16" class="submit_container">Build</button>
    </form>
</div>

<div class="wrapper_os">
    <div class="logo_os">
        <img src="{% static 'base/img/ubuntu.png' %}" width="80px" height="80px">
    </div>
    <div class="explain_os">
        <p>Ubuntu 18.04 LTS</p>
    </div>   
    <form method= "POST" action="{% url 'create_container' %}">
        {% csrf_token %}
        <button name="os" value="ubuntu18" class="submit_container">Build</button>
    </form>
</div>

<div class="wrapper_os">
    <div class="logo_os">
        <img src="{% static 'base/img/ubuntu.png' %}" width="80px" height="80px">
    </div>
    <div class="explain_os">
        <p>Ubuntu 20.04 LTS</p>
    </div>   
    <form method= "POST" action="{% url 'create_container' %}">
        {% csrf_token %}
        <button name="os" value="ubuntu20" class="submit_container">Build</button>
    </form>
</div>
    {% endif %}

{% endif %}

{% endblock content %}