web-master/web-backend/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
        # 홈 화면
        path('', views.HomeView.as_view(), name='home'),

        # 과목 메인 화면
        path('<title>/', views.SubjectView.as_view(), name='subject'),

        # 과목 상세 화면(과제 목록 확인, 과제 출제)
        path('<title>/<int:year>/<class_no>', views.SubjectDetailView.as_view(), name='subject_detail'),

        # 과제 등록 화면
        path('<title>/<int:year>/<class_no>/assignment/new/', views.AssignmentEditView.as_view(), name='assignment_new'),
        path('<title>/<int:year>/<class_no>/assignment/new/compile', views.compile, name='compile'),
        
        # 과제 상세 화면(과제 상세 확인, 과제 제출, 과제 수정)
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/', views.AssignmentView.as_view(), name='assignment_detail'),
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/input', views.assignment_input, name='assignment_input'),
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/assignment_input_output_setting', views.assignment_input_output_setting, name='assignment_input_output_setting'),
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/compile', views.assignment_compile, name='assignment_compile'),

        # 과제 점수 등록
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/jumsu/', views.AssignmentView.as_view(), name='jumsu'),

        # 제출된 과제 일괄 다운로드
        path('<title>/<int:year>/<class_no>/assignment/<int:pk>/download/', views.download_submitted_assignment_files, name='download'),

        # 게시글 상세 화면, 댓글 등록 화면
        path('<title>/boards/<int:pk>/', views.PostView.as_view(), name='post_detail'),
        
        # 게시글 등록 화면
        path('<title>/boards/new/', views.NewPostView.as_view(), name='post_new'),

        # 게시글 수정
        path('<title>/boards/<int:pk>/edit', views.PostEditView.as_view(), name='post_edit'),

        # 게시글 수정 화면에서 코드 리턴해주기
        path('<title>/boards/<int:pk>/edit/<filename>', views.PostEditView.as_view(), name='post_edit'),

        # 게시글 삭제
        path('<title>/boards/<int:pk>/delete', views.post_delete, name='post_delete'),

        # 게시글에서 코드 리턴해주기
        path('<title>/boards/<int:pk>/<filename>', views.get_source_code, name='get_source_code'),
        
        # 댓글 수정
        path('<title>/boards/<int:p_pk>/comment_edit/<int:c_pk>/', views.CommentEditView.as_view(), name='comment_edit'),

        # 댓글 삭제
        path('<title>/boards/<int:p_pk>/comment_delete/<int:c_pk>/', views.comment_delete, name='comment_delete'),
]

web-master/web-backend/boards/models.py
import datetime
import os

from django.db import models
from django.utils import timezone

from accounts.models import User

class Subject(models.Model):
    subject_no = models.IntegerField(
        primary_key=True,
        unique=True,
        null=False,
    )
    title = models.CharField(
        max_length=254,
        unique=True,
        null=False,
    )

    def __str__(self):
        return self.title


class DetailedSubject(models.Model):
    YEAR_CHOICES = []
    for r in range(2019, datetime.datetime.now().year+1):
        YEAR_CHOICES.append((r,r))
    
    SEMESTER = (('A10', 1), ('A20', 2))
    # CLASS_NUMBER = [(i,i) for i in range(1,6)]
    CLASS_NUMBER = []
    for i in range(1, 20):
        if i < 10:
            CLASS_NUMBER.append(('0' + str(i), '0' + str(i)))
        else :
            CLASS_NUMBER.append((str(i), str(i)))
    

    subject = models.ForeignKey(
        Subject,
        on_delete=models.SET_NULL,
        related_name='detailed_subject',
        # related_query_name='detaild_subjects',
        null=True,
    )
    year = models.IntegerField(
        choices=YEAR_CHOICES,
        null=False,
        default=datetime.datetime.now().year,
    )
    shyr = models.IntegerField(
        choices=((1,1),(2,2),(3,3),(4,4)),
        null=False,
        default=1,
    )
    semester = models.CharField(
        choices=SEMESTER,
        null=False,
        default='A10',
        max_length=3,
    )
    class_no = models.CharField(
        choices=CLASS_NUMBER,
        null=False,
        default='01',
        max_length=20,
    )
    professor = models.CharField(
        max_length=20,
    )
    admin = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        null = True,
    )

    class Meta:
        unique_together = ('subject', 'year', 'semester', 'class_no')
        # unique_together = ('subject', 'year', 'semester', 'class_no')
    
    def __str__(self):
        return self.subject.title + '(' + str(self.year) + ')-' + str(self.class_no) + '분반'
        # return self.subject.title + '-' + self.semester
        # return self.subject.title + '(' + str(self.year) + ') - ' + self.SEMESTERS[self.semester]

class Assignment(models.Model):
    # 7일 뒤로 제출일 디폴트 설정
    due_time = datetime.datetime.combine(datetime.date.today(), datetime.time(23,59,59)) + datetime.timedelta(days=6)

    subject = models.ForeignKey(
        DetailedSubject, 
        on_delete=models.CASCADE,
        related_name='assignments',
        null=False,
    )
    title = models.CharField(max_length=50)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    last_modified_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(default=due_time)
    point = models.IntegerField(default=100, null=False) # 배점
    code_submit_assignment = models.BooleanField(default=False)
    lang = models.CharField(max_length=30, default=None, null=True)

    def __str__(self):
        return self.title

def get_path(instance, filename):
    # 과목명/세부과목명/과제명/학생이름_파일명
    return '{0}/{1}/{2}/{3}_{4}{5}'.format(instance.assignment.subject.subject.title, instance.assignment.subject.__str__(), 
                instance.assignment, instance.student.student_id, instance.student.name, os.path.splitext(filename)[1])

class AssignmentSubmission(models.Model):
    assignment = models.ForeignKey(
        Assignment,
        on_delete=models.CASCADE,
        related_name='submissions',
        null=False,
    )
    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
    )
    point = models.IntegerField(null=True) # 학생이 획득한 점수
    original_file_name = models.CharField(max_length=254, null=True)
    file = models.FileField(upload_to=get_path, null=True)
    submission_date = models.DateTimeField(null=True, default=timezone.now)
    code_file_name = models.CharField(max_length=255, default=None, null=True)

    class Meta:
        unique_together = ('assignment', 'student',)

class Course(models.Model):
    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        related_name='courses'
    )
    subject = models.ForeignKey(
        DetailedSubject,
        on_delete=models.CASCADE,
    )

    class Meta:
        unique_together = ('student', 'subject')
        
    def __str__(self):
        return self.student.name + self.subject.subject.title

class Post(models.Model):
    subject = models.ForeignKey(
        Subject,
        on_delete=models.SET_NULL,
        null=True,
        related_name='posts',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        related_name='posts',
    )
    title = models.CharField(max_length=254)
    text = models.TextField()
    last_modified_date = models.DateTimeField(default=timezone.now)
    contain_code = models.BooleanField(default=False)
    lang = models.CharField(max_length=30, default=None, null=True)
    code_file_name = models.CharField(max_length=255, default=None, null=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.SET_NULL,
        null=True,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='comments'
    )
    text = models.TextField()
    last_modified_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

web-master/web-backend/boards/forms.py
from django import forms
from .models import Post, Comment, Assignment, AssignmentSubmission
from django.contrib.admin import widgets

class PostForm(forms.ModelForm):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Title', 'style':'margin-top:20px;'}))
    text = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'Content', 'rows':'25'}))
    contain_code = forms.BooleanField(required=False, label="", widget=forms.CheckboxInput(attrs={'class': 'some_class',}))

    class Meta:
        model = Post
        fields = ('title', 'text', 'contain_code')


class CommentForm(forms.ModelForm):
    text = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder':'Comment', 'rows':'2'}))
    class Meta:
        model = Comment
        fields = ('text',)

class AssignmentForm(forms.ModelForm):
    title = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'Title', 'style':'margin-top:20px;'}))
    text = forms.CharField(label=False, widget=forms.Textarea(attrs={'placeholder': 'Content', 'rows':'25'}))
    code_submit_assignment = forms.BooleanField(required=False, label=False, help_text=" 코드 제출 과제")

    class Meta:
        model = Assignment
        fields = ('title', 'text', 'point', 'due_date', 'code_submit_assignment')

class AssignmentSubmissionForm(forms.ModelForm):
    file = forms.FileField(
        widget=forms.ClearableFileInput()
    )

    class Meta:
        model = AssignmentSubmission
        fields = ('file',)

web-master/web-backend/boards/templates/boards/assignment_new.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New Assignment{% endblock title %}


{% block style %}
<style>

.code-editor-invisible {
    display: none;
}

.area {
	width: 49%;
	height: 300px;
	resize: none;
}

#id_title, #id_text {
    width: 100%;
}

#id_text {
    max-height: 100%;
}

</style>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'webcompiler/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'webcompiler/css/my_style.css' %}" />


	
<script src="{% static 'webcompiler/js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'webcompiler/js/bootstrap.min.js' %}"></script>
<script src="{% static 'webcompiler/ace-builds/src-noconflict/ace.js' %}"></script>

<script>
    var editor = null;
    var source_code = null;
    var input = null;
    var language = {}
    var selectedLang = "PYTHON"
    language['PYTHON'] = "def solution(input):\n\t";
    language['R'] = 'cat("Hello World")\n';
    language['C'] = '#include <stdio.h>\n\nint main(void) \n{\n	printf("Hello World!\\n");\n	return 0;\n}\n';
    language['CPP'] = '#include <iostream>\nusing namespace std;\n\nint main()\n{\n     cout << "Hello World!" << endl;\n     return 0;\n}\n';
    language['CSHARP'] = 'using System;\nusing System.Numerics;\nclass Test {\n	static void Main(string[] args)	{\n	   /*\n		* \n		Read input from stdin and provide input before running\n		var line1 = System.Console.ReadLine().Trim();\n		var N = Int32.Parse(line1);\n		for (var i = 0; i < N; i++) {\n		System.Console.WriteLine("hello world");\n		}\n		*/\n\n		System.Console.WriteLine("Hello World!\\n");\n	}\n}\n';
    language['JAVA'] = 'class TestClass {\n    public static void main(String args[] ) throws Exception {\n        System.out.println("Hello World!");\n    }\n}\n';
    language['JAVASCRIPT'] = "importPackage(java.io);\nimportPackage(java.lang);\n\nprint ('Hello World!\\n');\n";
    language['PHP'] = '<?php\n\necho "Hello World!";\n\n?>\n';
    language['GO'] = 'package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello World")\n}\n';

    var e = {
        "C":"c","CPP":"cpp","CLOJURE":"clj","CSS":"css","CSHARP":"cs",
        "GO":"go","HASKELL":"hs","JAVA":"java","JAVASCRIPT":"js",
        "LISP":"scm","OBJECTIVEC":"m","PERL":"pl","PHP":"php",
        "PYTHON":"py","RUBY":"rb","R":"r","RUST":"rs","SCALA":"scala",
        "TEXT":"txt"
    };

    // --- initialize
    $(document).ready(function(){
        // submit post
        $("#submit-button").click(function(){
            createAssignment();
        });

        // show/hide code editor
        $("#id_code_submit_assignment").click(function() {
            showHideCodeEditor();
        });

        // compile and show output
        $("#compile-code-button").click(function() {
            compileCode();
        });

        // download code
        $("#download").click(function(){
            download();
        });

        // change language
        $("#lang").change(function(){
            changeLanguage();
        });

        // change theme
        $("#theme").change(function(){
            changeTheme();
        });

        
        // ------From Ace Documentation on inserting the editor------//
        // document.getElementById("code").innerHTML = language[selectedLang];
        ace.require("ace/ext/language_tools");
        editor = ace.edit("editor");
        var ongoing = false;
        editor.setTheme("ace/theme/dawn");
        editor.session.setMode("ace/mode/python");
        editor.getSession().setTabSize(5);
        source_code = editor.getValue();
        editor.setFontSize(14);
        editor.setValue(language[selectedLang],-1);
        // var StatusBar = ace.require("ace/ext/statusbar").StatusBar;
        // var statusBar = new StatusBar(editor, document.getElementById("editor-statusbar"));
		editor.session.getSelection().clearSelection();
    });


    //To get the current contents in the editor
    function updateContent(){
        source_code = editor.getValue();
        input = document.getElementById("input-area").value;
    }

    function createAssignment(){
        // compileCode();

        var title = document.getElementById("id_title");
        var text = document.getElementById("id_text");
        if(title.value == "" || text.value == "" || title.value == null || text.value==null) {
            alert("제목이나 내용을 확안히세요!");
            return;
        }

        var form = document.getElementById('my-post-form');

        var input = document.createElement("input")
        input.type = "hidden";
        input.value = selectedLang;
        input.name = "lang";
        form.append(input);
        
        form.submit();
    }

    function compileCode() {
        updateContent();
        
        var token = $(":input[name='csrfmiddlewaretoken']").val();
        var run_data = {
                source: source_code,
                lang: selectedLang,
                input: input,
                csrfmiddlewaretoken:token
        };
        
        $.ajax({
            type:'POST',
            url:'compile',
            data:{
                lang: selectedLang,
                code: source_code,
                input: input,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json){
                document.getElementById('output-area').value = json.output
            },
            error : function(xhr,errmsg,err) {
                document.getElementById('output-area').value = "에러 발생"
            }
        });
    }
    

    function download() {
        updateContent();

        var element = document.createElement('a');
        element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(source_code));
        element.setAttribute('download', "file." + e[selectedLang]);
        element.style.display = 'none';
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    }

    function showHideCodeEditor() {
        var code = document.getElementById('code-editor')
        if(document.getElementById('id_code_submit_assignment').checked) {
            code.classList.remove('code-editor-invisible');
            // document.getElementById('submit-button').setAttribute("")
        } else {
            code.classList.add('code-editor-invisible');
        }
    }

    //When Changing the language
    function changeLanguage() {
        selectedLang = $("#lang").val();
        document.getElementById("code").innerHTML = language[selectedLang];
        editor.setValue(language[selectedLang],-1);

        if(selectedLang == "C" || selectedLang == "CPP"){
            editor.getSession().setMode("ace/mode/c_cpp");
        }
        else{
            editor.getSession().setMode("ace/mode/" + selectedLang.toLowerCase());
        }

        editor.session.getSelection().clearSelection();
    }

    // When changing the theme
    function changeTheme() {
        themeSelected = $("#theme").val();
        if(themeSelected == "Light"){
            editor.setTheme("ace/theme/dawn");
        }
        else if(themeSelected == "Monokai"){
            editor.setTheme("ace/theme/monokai");
        }
        else if(themeSelected == "Solarised Light"){
            editor.setTheme("ace/theme/solarized_light");
        }
        else if(themeSelected == "Twilight"){
            editor.setTheme("ace/theme/twilight");
        }
    }

</script>
{% endblock style %}

{% block content %}
	<h2>New Assignment</h2>
	<form method="POST" class="post-form" id="my-post-form">{% csrf_token %}
		{{ form.as_p }}
    </form>
    <div class="container pt-5 code-editor-invisible" id="code-editor">

        <div id="topbar">

            <div class="lang-choose">
                <select class="form-control" name="lang" id="lang">
                    <option value="PYTHON" selected>Python (python 3.7)</option>
                    <option value="R">R (RScript 3.6.2)</option>
                    <option value="C">C (gcc 4.8.4)</option>
                    <option value="CPP" >C++ (g++ 4.8.4)</option>
                    <option value="CSHARP">C# (mono 3.2.8)</option>
                    <option value="JAVA">Java (openjdk 1.7.0_09)</option>
                    <option value="JAVASCRIPT">JavaScript (Rhino 1.7)</option>
                    <option value="PHP">PHP (php 5.5.9)</option>
                    <option value="GO">Go (go 1.4.2)</option>
                    <option value="TEXTFILE">Text</option>
                </select>
            </div> 
            
            <div id="settings">
                <div class="theme-choose">
                    <select class="form-control" name="theme" id="theme">
                        <option value="Light" selected>Light</option>
                        <option value="Monokai">Monokai</option>
                        <option value="Solarised Light">Solarised Light</option>
                        <option value="Twilight">Twilight</option>
                    </select>
                </div>

                <a class="" id="download">
                    download code
                    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                </a>
            </div>
            
        </div>
        
        <textarea name="code" class="form-control" id="code" placeholder="code" rows="0" style="display:none;" ></textarea>

        <pre id="editor"></pre>

        <div>
            <textarea class="area" id="input-area" placeholder="첫 줄에는 전체 테스트 케이스를 입력해주세요.&#13;&#10;한 줄에 하나의 테스트케이스를 입력해주세요."></textarea>
            <textarea class="area" id="output-area" readonly></textarea><br>
        </div>

        <button class="save btn btn-default" id="compile-code-button">Run</button>

        <!-- <div id="editor-statusbar"></div> -->
    </div>
    <button type="submit" class="save btn btn-default" id="submit-button">Save</button>    

{% endblock %}

web-master/web-backend/boards/templates/boards/post_detail.html
{% extends "boards/base_boards.html" %}
{% load static %}

{% block title %}{{ post.title }}{% endblock title %}
{% block style %}

<style>
	#id_text {
		width:100%;
	}
</style>

{% if post.contain_code %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'webcompiler/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'webcompiler/css/my_style.css' %}" />

<script src="{% static 'webcompiler/js/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'webcompiler/js/bootstrap.min.js' %}"></script>
<script src="{% static 'webcompiler/ace-builds/src-noconflict/ace.js' %}"></script>


<script>
	var editor = null;
	var source_code = null;
	var selectedLang = "{{ post.lang }}";
	
	// --- initialize
	$(document).ready(function(){
		// download code
		$("#download").click(function(){
			download();
		});

		// change theme
		$("#theme").change(function(){
			changeTheme();
		});

		
		readTextFile();
		ace.require("ace/ext/language_tools");
		editor = ace.edit("editor");
		var ongoing = false;
		editor.setTheme("ace/theme/dawn");
		setLanguage();
		document.getElementById("lang").value = selectedLang;
		removeOtherLang();
		editor.getSession().setTabSize(5);
		editor.setFontSize(14);
		editor.setValue(source_code);
		editor.setReadOnly(true);
		editor.session.getSelection().clearSelection();
	});

	function removeOtherLang() {
		var count = document.getElementById("lang").options.length;
		var selected = document.getElementById("lang").options.selectedIndex;
		for(var i = 0; i < count; i++) {
			if(i < selected) document.getElementById("lang").options.remove(0);
			else if(i == selected) continue;
			else document.getElementById("lang").options.remove(1);
		}
	}

	function readTextFile() {
		var rawFile = new XMLHttpRequest();
		rawFile.open("GET", "{{ post.code_file_name }}", false);
		rawFile.onreadystatechange = function() {
			if(rawFile.readyState === 4) {
				if(rawFile.status === 200 || rawFile.status === 0) {
					source_code = rawFile.responseText;
				}
			}
		}
		rawFile.send(null);
	}


	//To get the current contents in the editor
	function updateContent(){
		source_code = editor.getValue();
	}	

	function download() {
		updateContent();

		var e = {
			"C":"c","CPP":"cpp","CLOJURE":"clj","CSS":"css","CSHARP":"cs",
			"GO":"go","HASKELL":"hs","JAVA":"java","JAVASCRIPT":"js",
			"LISP":"scm","OBJECTIVEC":"m","PERL":"pl","PHP":"php",
			"PYTHON":"py","RUBY":"rb","R":"r","RUST":"rs","SCALA":"scala",
			"TEXT":"txt"
		};

		var element = document.createElement('a');
		element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(source_code));
		element.setAttribute('download', "file." + e[selectedLang]);
		element.style.display = 'none';
		document.body.appendChild(element);
		element.click();
		document.body.removeChild(element);
	}

	// set language
	function setLanguage() {
		if(selectedLang == "C" || selectedLang == "CPP"){
			editor.getSession().setMode("ace/mode/c_cpp");
		}
		else{
			editor.getSession().setMode("ace/mode/" + selectedLang.toLowerCase());
		}

		editor.session.getSelection().clearSelection();
	}

	// When changing the theme
	function changeTheme() {
		themeSelected = $("#theme").val();
		if(themeSelected == "Light"){
			editor.setTheme("ace/theme/dawn");
		}
		else if(themeSelected == "Monokai"){
			editor.setTheme("ace/theme/monokai");
		}
		else if(themeSelected == "Solarised Light"){
			editor.setTheme("ace/theme/solarized_light");
		}
		else if(themeSelected == "Twilight"){
			editor.setTheme("ace/theme/twilight");
		}
	}

</script>
{% endif %}

{% endblock style %}



{% block content %}

<div>
	<h2>{{ post.title }}</h2>
	<h6>{{ post.author.name }} ({{ post.last_modified_date }})
		{% if user == post.author %}
			<a href="{% url 'boards:post_edit' title=post.subject.title pk=post.pk %}">수정</a>
			<a href="{% url 'boards:post_delete' title=post.subject.title pk=post.pk %}">삭제</a>
		{% endif %}
	</h6>
	
	<p>{{ post.text | linebreaksbr }}</p>
	

	{% if post.contain_code %}
	<div class="container pt-5" id="code-editor">

		<div id="topbar">

			<div class="lang-choose">
				<select class="form-control" name="lang" id="lang">
					<option value="PYTHON">Python (python 3.7)</option>
					<option value="R">R (RScript 3.6.2)</option>
					<option value="C">C (gcc 4.8.4)</option>
					<option value="CPP" >C++ (g++ 4.8.4)</option>
					<option value="CSHARP">C# (mono 3.2.8)</option>
					<option value="JAVA">Java (openjdk 1.7.0_09)</option>
					<option value="JAVASCRIPT">JavaScript (Rhino 1.7)</option>
					<option value="PHP">PHP (php 5.5.9)</option>
					<option value="GO">Go (go 1.4.2)</option>
					<option value="TEXTFILE">Text</option>
				</select>
			</div> 
			
			<div id="settings">
				<div class="theme-choose">
					<select class="form-control" name="theme" id="theme">
						<option value="Light" selected>Light</option>
						<option value="Monokai">Monokai</option>
						<option value="Solarised Light">Solarised Light</option>
						<option value="Twilight">Twilight</option>
					</select>
				</div>

				<a class="" id="download">
					download code
					<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
				</a>
			</div>
			
		</div>
		
		<textarea name="code" class="form-control" id="code" placeholder="code" rows="0" style="display:none;" ></textarea>
		
		<!-- <input type="code" class="form-control" id="code" rows="0"  ></textarea> -->

		<pre id="editor"></pre>

		<!-- <div id="editor-statusbar"></div> -->
	</div>

	{% endif %}


</div>

<br><br>

<div>
	<h3>Comments</h3>
	{% for comment in comments %}
		<div>
		{{ comment.author }} ({{ comment.last_modified_date }})
		{% if user == comment.author %}
			<a href="{% url 'boards:comment_edit' title=post.subject.title p_pk=post.pk c_pk=comment.pk %}"><button method="GET">수정</button></a>
			<a href="{% url 'boards:comment_delete' title=post.subject.title p_pk=post.pk c_pk=comment.pk %}"><button method="POST">삭제</button></a>
		{% endif %}
		<p>{{ comment.text | linebreaksbr }}</p>
		</div>
	{% endfor %}
	<form method="POST">{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">댓글달기</button>
	</form>
</div>



{% endblock content %}

web-master/web-backend/boards/templates/boards/subject.html
{% extends "boards/base_boards.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div>
	<h2>{{ title }}</h2>
</div>


{% for subject in subjects %}
	<h3><a href="{% url 'boards:subject_detail' title=subject.subject.title year=subject.year class_no=subject.class_no %}">{{ title }} {{ subject.class_no}}분반 ({{ subject.year }})</a></h3>
{% endfor %}

<br><br>
<div>
	<div><h1>게시판</h1></div>
	<a href="{% url 'boards:post_new' title=title %}">글쓰기</a>
	{% for post in posts %}
	<h3><a href="{% url 'boards:post_detail' title=title pk=post.pk %}">{{ post.title }}</a></h3>
	{% endfor %}
</div>

{% endblock content %}